services:
  db:
    image: postgres:alpine
    environment: { POSTGRES_PASSWORD: postgres }
    ports: [ '5432:5432' ]
    restart: always

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080